---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

clickhouse_path_configdir: "/etc/clickhouse-server"
clickhouse_path_logdir: "/var/log/clickhouse-server"
clickhouse_path_data: "{{ clickhouse_path_base }}/clickhouse/"
clickhouse_path_tmp: "{{ clickhouse_path_base }}/clickhouse/tmp/"
clickhouse_service: 'clickhouse-server.service'
